import { motion } from "motion/react";
import { Brain, Target, Zap, Users } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Roadmaps",
    description: "Custom learning paths generated by intelligent algorithms tailored to your goals."
  },
  {
    icon: Target,
    title: "Adaptive Questioning",
    description: "Questions that evolve based on your progress and learning patterns."
  },
  {
    icon: Zap,
    title: "Instant Feedback",
    description: "Real-time insights and explanations to accelerate your understanding."
  },
  {
    icon: Users,
    title: "Personalized Experience",
    description: "Learning that adapts to your unique style and pace for maximum retention."
  }
];

export function About() {
  return (
    <section className="py-32 px-6 relative">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-20"
        >
          <h2 className="text-5xl font-bold text-white mb-6">
            Why Choose <span className="text-[#BEDCE4]">Catalyst</span>?
          </h2>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Experience the next generation of learning with AI that understands how you learn best.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              whileHover={{ 
                y: -10,
                scale: 1.02
              }}
              className="group relative"
            >
              <div className="bg-[#2A2A2A] border border-[#46675D]/20 rounded-2xl p-8 h-full relative overflow-hidden transition-all duration-300 hover:border-[#46675D]/40">
                {/* Parallax background effect */}
                <motion.div
                  className="absolute inset-0 bg-gradient-to-br from-[#46675D]/5 to-[#BEDCE4]/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300"
                  whileHover={{ scale: 1.1 }}
                />
                
                <div className="relative z-10">
                  <div className="inline-flex p-3 bg-[#46675D]/10 border border-[#46675D]/20 rounded-xl mb-6 group-hover:scale-110 transition-transform duration-300">
                    <feature.icon className="w-6 h-6 text-[#BEDCE4]" />
                  </div>

                  <h3 className="text-xl font-semibold text-white mb-4 group-hover:text-[#BEDCE4] transition-colors duration-300">
                    {feature.title}
                  </h3>
                  
                  <p className="text-gray-300 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}